# Generated by Django 5.2.17 on 2026-09-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('ativa', models.BooleanField(default=True)),
                ('monitores', models.ManyToManyField(blank=True, related_name='disciplinas_monitoradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('resposta', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('em_atendimento', 'Em atendimento'), ('respondida', 'Respondida'), ('encerrada', 'Encerrada')], default='aberta', max_length=20, verbose_name='situação')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duvidas_abertas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duvidas', to='duvidas.disciplina')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duvidas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='monitor responsável')),
            ],
            options={
                'verbose_name': 'dúvida',
                'ordering': ['-criada_em'],
                'permissions': [('ver_todas_duvidas', 'Pode ver todas as dúvidas')],
            },
        ),
    ]
