# Generated by Django 5.2.17 on 2026-09-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duvidas', '0001_disciplina_duvida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado')], verbose_name='dia da semana')),
                ('inicio', models.TimeField(verbose_name='início')),
                ('fim', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='duvidas.disciplina')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atendimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'horário de atendimento',
                'verbose_name_plural': 'horários de atendimento',
                'ordering': ['dia_semana', 'inicio'],
            },
        ),
    ]
